package com.theplugos.cashierhub.native

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.nio.charset.StandardCharsets
import java.math.BigInteger
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.MessageDigest
import java.security.PrivateKey
import java.security.Principal
import java.security.SecureRandom
import java.security.Signature
import java.util.Date
import java.util.UUID
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext
import javax.net.ssl.SSLEngine
import javax.net.ssl.X509ExtendedKeyManager
import javax.net.ssl.X509KeyManager
import javax.security.auth.x500.X500Principal
import java.net.Socket
import java.security.cert.X509Certificate

/**
 * Keeps Hub signing and database-wrap keys non-exportable in Android Keystore.
 * The SQLCipher passphrase is random, wrapped at rest, and only unwrapped while
 * SQLCipher opens the database.
 */
class HubKeyManager(private val context: Context) {
    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
    private val preferences = context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE)

    fun signingPublicKeyBase64(): String = HubWireEncoding.encode(signingKeyPair().public.encoded)

    /** Opaque, persistent public identifier; it is independent from Android
     * hardware IDs and is never manufactured by browser storage. */
    fun hubDeviceId(): String {
        val existing = preferences.getString(HUB_DEVICE_ID, null)
        if (existing != null && existing.matches(Regex("^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$"))) return existing
        val generated = "hub-${UUID.randomUUID()}"
        check(preferences.edit().putString(HUB_DEVICE_ID, generated).commit()) {
            "The Hub device ID could not be persisted."
        }
        return generated
    }

    /**
     * The LAN server certificate is generated by Android Keystore and its
     * private key never leaves the device. Cloud enrollment signs this public
     * certificate fingerprint into the authorization bundle; peers pin that
     * signed binding instead of trusting a LAN certificate authority.
     */
    fun localTlsCertificateBase64(): String = HubWireEncoding.encode(localTlsCertificate().encoded)

    fun localTlsCertificateFingerprint(): String = MessageDigest.getInstance("SHA-256")
        .digest(localTlsCertificate().encoded)
        .joinToString(separator = "") { byte -> "%02x".format(byte) }

    fun localTlsServerContext(): SSLContext {
        localTlsKeyPair()
        val keyManagers = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm()).run {
            init(keyStore, null)
            keyManagers
        }
        val delegate = keyManagers.filterIsInstance<X509KeyManager>().firstOrNull()
            ?: error("The Android Keystore did not expose an X509 key manager for the Hub TLS certificate.")
        return SSLContext.getInstance("TLS").apply {
            init(arrayOf(PinnedAliasKeyManager(delegate, LOCAL_TLS_ALIAS)), null, SecureRandom())
        }
    }

    fun sign(message: ByteArray): ByteArray {
        val signature = Signature.getInstance("SHA256withECDSA")
        signature.initSign(signingPrivateKey())
        signature.update(message)
        return signature.sign()
    }

    fun databasePassphrase(): String {
        val storedCiphertext = preferences.getString(DATABASE_PASSPHRASE_CIPHERTEXT, null)
        val storedIv = preferences.getString(DATABASE_PASSPHRASE_IV, null)
        if (storedCiphertext != null && storedIv != null) {
            return decrypt(
                Base64.decode(storedCiphertext, Base64.NO_WRAP),
                Base64.decode(storedIv, Base64.NO_WRAP)
            )
        }

        val rawPassphrase = ByteArray(32).also { SecureRandom().nextBytes(it) }
        val passphrase = Base64.encodeToString(rawPassphrase, Base64.NO_WRAP)
        rawPassphrase.fill(0)
        val encrypted = encrypt(passphrase.toByteArray(StandardCharsets.UTF_8))
        preferences.edit()
            .putString(DATABASE_PASSPHRASE_CIPHERTEXT, Base64.encodeToString(encrypted.ciphertext, Base64.NO_WRAP))
            .putString(DATABASE_PASSPHRASE_IV, Base64.encodeToString(encrypted.iv, Base64.NO_WRAP))
            .commit()
        return passphrase
    }

    private fun signingKeyPair(): KeyPair {
        val existing = keyStore.getEntry(SIGNING_ALIAS, null) as? KeyStore.PrivateKeyEntry
        if (existing != null) return KeyPair(existing.certificate.publicKey, existing.privateKey)

        val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, ANDROID_KEYSTORE)
        generator.initialize(
            KeyGenParameterSpec.Builder(
                SIGNING_ALIAS,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setDigests(KeyProperties.DIGEST_SHA256)
                .build()
        )
        return generator.generateKeyPair()
    }

    private fun signingPrivateKey(): PrivateKey {
        signingKeyPair()
        val entry = keyStore.getEntry(SIGNING_ALIAS, null) as? KeyStore.PrivateKeyEntry
            ?: error("The Hub signing key is unavailable.")
        return entry.privateKey
    }

    private fun localTlsKeyPair(): KeyPair {
        val existing = keyStore.getEntry(LOCAL_TLS_ALIAS, null) as? KeyStore.PrivateKeyEntry
        if (existing != null) return KeyPair(existing.certificate.publicKey, existing.privateKey)

        val now = Date()
        val expiry = Date(now.time + LOCAL_TLS_CERTIFICATE_VALIDITY_MS)
        val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, ANDROID_KEYSTORE)
        generator.initialize(
            KeyGenParameterSpec.Builder(
                LOCAL_TLS_ALIAS,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setDigests(KeyProperties.DIGEST_SHA256)
                .setCertificateSubject(X500Principal("CN=ThePlugOS Cashier Hub"))
                .setCertificateSerialNumber(BigInteger(160, SecureRandom()))
                .setCertificateNotBefore(now)
                .setCertificateNotAfter(expiry)
                .build()
        )
        return generator.generateKeyPair()
    }

    private fun localTlsCertificate() = (keyStore.getEntry(LOCAL_TLS_ALIAS, null) as? KeyStore.PrivateKeyEntry)
        ?.certificate ?: run {
            localTlsKeyPair()
            (keyStore.getEntry(LOCAL_TLS_ALIAS, null) as? KeyStore.PrivateKeyEntry)
                ?.certificate ?: error("The Hub TLS certificate is unavailable.")
        }

    private fun wrappingKey(): SecretKey {
        val existing = keyStore.getKey(DATABASE_WRAP_ALIAS, null) as? SecretKey
        if (existing != null) return existing

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                DATABASE_WRAP_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun encrypt(plaintext: ByteArray): EncryptedValue {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())
        return EncryptedValue(cipher.doFinal(plaintext), cipher.iv)
    }

    private fun decrypt(ciphertext: ByteArray, iv: ByteArray): String {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, wrappingKey(), GCMParameterSpec(128, iv))
        return String(cipher.doFinal(ciphertext), StandardCharsets.UTF_8)
    }

    private data class EncryptedValue(val ciphertext: ByteArray, val iv: ByteArray)

    private class PinnedAliasKeyManager(
        private val delegate: X509KeyManager,
        private val alias: String
    ) : X509ExtendedKeyManager() {
        override fun chooseEngineClientAlias(keyType: Array<out String>?, issuers: Array<out Principal>?, engine: SSLEngine?): String? = null
        override fun chooseEngineServerAlias(keyType: String?, issuers: Array<out Principal>?, engine: SSLEngine?): String? = alias
        override fun chooseClientAlias(keyType: Array<out String>?, issuers: Array<out Principal>?, socket: Socket?): String? = null
        override fun chooseServerAlias(keyType: String?, issuers: Array<out Principal>?, socket: Socket?): String? = alias
        override fun getCertificateChain(requestedAlias: String?): Array<X509Certificate>? = delegate.getCertificateChain(requestedAlias)
        override fun getClientAliases(keyType: String?, issuers: Array<out Principal>?): Array<String>? = delegate.getClientAliases(keyType, issuers)
        override fun getPrivateKey(requestedAlias: String?): PrivateKey? = delegate.getPrivateKey(requestedAlias)
        override fun getServerAliases(keyType: String?, issuers: Array<out Principal>?): Array<String>? = delegate.getServerAliases(keyType, issuers)
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val SIGNING_ALIAS = "theplugos.cashier-hub.signing.v1"
        const val LOCAL_TLS_ALIAS = "theplugos.cashier-hub.local-tls.v1"
        const val DATABASE_WRAP_ALIAS = "theplugos.cashier-hub.database-wrap.v1"
        const val PREFERENCES = "theplugos.cashier-hub.keystore"
        const val DATABASE_PASSPHRASE_CIPHERTEXT = "database-passphrase-ciphertext"
        const val DATABASE_PASSPHRASE_IV = "database-passphrase-iv"
        const val HUB_DEVICE_ID = "hub-device-id"
        const val LOCAL_TLS_CERTIFICATE_VALIDITY_MS = 10L * 365L * 24L * 60L * 60L * 1000L
    }
}
